version: '3.8'

services:
  couchdb:
    image: couchdb:3.5
    container_name: obsidian-couchdb
    restart: unless-stopped
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_SECRET=${COUCHDB_SECRET}
      - COUCHDB_JWT_AUTH_SECRET=${JWT_HMAC_SECRET}
    volumes:
      - ./data:/opt/couchdb/data
      - ./local.ini:/opt/couchdb/etc/local.ini
      - ./backups:/backups
    ports:
      - "127.0.0.1:5984:5984"
    networks:
      - obsidian-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  obsidian-net:
    driver: bridge
